services:
  app:
    build:
      context: .
      target: development
    container_name: fabrica-dev-door
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - fabrica-network
    restart: on-failure

networks:
  fabrica-network:
    driver: bridge
